version: '3.8'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file: ./.env
    environment:
      - name=value
    depends_on:
      - mysql
    
  client:
    build:
      context: ./frontend
      dockerfile:  Dockerfile
    container_name: frontend
    ports:
      - "8084:80"
    depends_on:
      - server