version: '3.8'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file: ./.env
    environment:
      - name=value
    depends_on:
      - mysql
    
  client:
    build:
      context: ./frontend
      dockerfile:  Dockerfile
    container_name: frontend
    ports:
      - "8084:80"
    depends_on:
      - server
    
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./mydata:/data/db